/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/tenders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tenders
         * @description Return stored tenders with pagination, filtering, sorting, and search.
         */
        get: operations["get_tenders_api_v1_tenders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenders/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tender Stats
         * @description Return aggregate tender counts by evaluation outcome, for dashboards.
         */
        get: operations["get_tender_stats_api_v1_tenders_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenders/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tender Facets
         * @description Return the distinct category and state values actually present in
         *     the data, for populating real dropdown filters in the dashboard
         *     instead of free-text inputs.
         */
        get: operations["get_tender_facets_api_v1_tenders_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenders/{tender_id}/evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tender Evaluation
         * @description Return the evaluation for a tender.
         */
        get: operations["get_tender_evaluation_api_v1_tenders__tender_id__evaluation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenders/{tender_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tender
         * @description Return a single tender by its business identifier.
         */
        get: operations["get_tender_api_v1_tenders__tender_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ingestion Status
         * @description Return the most recently started ingestion run.
         */
        get: operations["get_ingestion_status_api_v1_ingestion_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestionRunResponse */
        IngestionRunResponse: {
            /** Id */
            id: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Status */
            status: string;
            /** Discovered */
            discovered: number;
            /** Successful */
            successful: number;
            /** Failed */
            failed: number;
            /** Skipped */
            skipped: number;
            /** Error */
            error: string | null;
        };
        /** RuleResultResponse */
        RuleResultResponse: {
            /** Rule Name */
            rule_name: string;
            /** Passed */
            passed: boolean;
            /** Reason */
            reason: string;
        };
        /** TenderEvaluationResponse */
        TenderEvaluationResponse: {
            /** Id */
            id: number;
            /** Tender Id */
            tender_id: number;
            /** Keyword Status */
            keyword_status: string;
            /** Eligibility Status */
            eligibility_status: string;
            /** Final Status */
            final_status: string;
            /** Matched Keywords */
            matched_keywords: string[];
            /** Excluded Keywords */
            excluded_keywords: string[];
            /** Passed Rules */
            passed_rules: components["schemas"]["RuleResultResponse"][];
            /** Failed Rules */
            failed_rules: components["schemas"]["RuleResultResponse"][];
            /** Unknown Rules */
            unknown_rules: components["schemas"]["RuleResultResponse"][];
            /** Reasons */
            reasons: string[];
            /**
             * Evaluated At
             * Format: date-time
             */
            evaluated_at: string;
        };
        /**
         * TenderFacetsResponse
         * @description Distinct category/state values present in the data.
         */
        TenderFacetsResponse: {
            /** Categories */
            categories: string[];
            /** States */
            states: string[];
        };
        /**
         * TenderListResponse
         * @description Paginated, filterable list of tenders.
         */
        TenderListResponse: {
            /** Items */
            items: components["schemas"]["TenderResponse"][];
            /** Total */
            total: number;
            /** Skip */
            skip: number;
            /** Limit */
            limit: number;
        };
        /** TenderResponse */
        TenderResponse: {
            /** Id */
            id: number;
            /** Tender Id */
            tender_id: string;
            /** Tender Title */
            tender_title: string;
            /** Organization */
            organization?: string | null;
            /** Tender Reference Number */
            tender_reference_number?: string | null;
            /** Tender Url */
            tender_url: string;
            /** Published Date */
            published_date?: string | null;
            /** Bid Submission Start Date */
            bid_submission_start_date?: string | null;
            /** Bid Submission End Date */
            bid_submission_end_date?: string | null;
            /** Opening Date */
            opening_date?: string | null;
            /** Estimated Value */
            estimated_value?: number | null;
            /** Earnest Money Deposit */
            earnest_money_deposit?: number | null;
            /** Tender Fee */
            tender_fee?: number | null;
            /** Currency */
            currency?: string | null;
            /** Tender Type */
            tender_type?: string | null;
            /** Category */
            category?: string | null;
            /** Procurement Type */
            procurement_type?: string | null;
            /** State */
            state?: string | null;
            /** City */
            city?: string | null;
            /** Work Location */
            work_location?: string | null;
            /** Status */
            status?: string | null;
            /** Withdrawal Allowed */
            withdrawal_allowed?: boolean | null;
            /** Form Of Contract */
            form_of_contract?: string | null;
            /** Payment Mode */
            payment_mode?: string | null;
            /** Work Description */
            work_description?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            evaluation?: components["schemas"]["TenderEvaluationResponse"] | null;
        };
        /**
         * TenderStatsResponse
         * @description Aggregate counts of tenders by evaluation outcome, for dashboards.
         */
        TenderStatsResponse: {
            /** Total */
            total: number;
            /** Qualified */
            qualified: number;
            /** Filtered Out */
            filtered_out: number;
            /** Not Eligible */
            not_eligible: number;
            /** Review Required */
            review_required: number;
            /** Unevaluated */
            unevaluated: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_tenders_api_v1_tenders_get: {
        parameters: {
            query?: {
                /** @description Number of tenders to skip */
                skip?: number;
                /** @description Maximum number of tenders to return */
                limit?: number;
                /** @description Case-insensitive substring match against tender title or organization */
                search?: string | null;
                /** @description Filter by evaluation final status, e.g. QUALIFIED, FILTERED_OUT, NOT_ELIGIBLE, REVIEW_REQUIRED */
                final_status?: string | null;
                /** @description Filter by tender category */
                category?: string | null;
                /** @description Filter by tender state */
                state?: string | null;
                /** @description Filter by tender status, e.g. Open */
                status?: string | null;
                /** @description Field to sort by */
                sort_by?: "id" | "created_at" | "updated_at" | "estimated_value" | "bid_submission_end_date";
                /** @description Sort direction */
                sort_order?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenderListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tender_stats_api_v1_tenders_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenderStatsResponse"];
                };
            };
        };
    };
    get_tender_facets_api_v1_tenders_facets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenderFacetsResponse"];
                };
            };
        };
    };
    get_tender_evaluation_api_v1_tenders__tender_id__evaluation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenderEvaluationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tender_api_v1_tenders__tender_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ingestion_status_api_v1_ingestion_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRunResponse"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
