"""create tender evaluations table

Revision ID: cc03b14d7866
Revises: 5f7da7b6288e
Create Date: 2026-08-19 12:43:32.022150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc03b14d7866'
down_revision: Union[str, Sequence[str], None] = '5f7da7b6288e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('keyword_status', sa.String(length=50), nullable=False),
    sa.Column('eligibility_status', sa.String(length=50), nullable=False),
    sa.Column('final_status', sa.String(length=50), nullable=False),
    sa.Column('matched_keywords', sa.JSON(), nullable=False),
    sa.Column('excluded_keywords', sa.JSON(), nullable=False),
    sa.Column('passed_rules', sa.JSON(), nullable=False),
    sa.Column('failed_rules', sa.JSON(), nullable=False),
    sa.Column('unknown_rules', sa.JSON(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_evaluations_tender_id'), 'tender_evaluations', ['tender_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tender_evaluations_tender_id'), table_name='tender_evaluations')
    op.drop_table('tender_evaluations')
    # ### end Alembic commands ###
