"""create tenders table

Revision ID: ff90fdd64250
Revises: 
Create Date: 2026-08-10 17:30:33.048067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff90fdd64250'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tender_id', sa.String(length=255), nullable=False),
    sa.Column('tender_title', sa.String(length=1000), nullable=False),
    sa.Column('organization', sa.String(length=1000), nullable=True),
    sa.Column('tender_reference_number', sa.String(length=500), nullable=True),
    sa.Column('tender_url', sa.String(length=2000), nullable=False),
    sa.Column('published_date', sa.String(length=100), nullable=True),
    sa.Column('bid_submission_start_date', sa.String(length=100), nullable=True),
    sa.Column('bid_submission_end_date', sa.String(length=100), nullable=True),
    sa.Column('opening_date', sa.String(length=100), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('earnest_money_deposit', sa.Float(), nullable=True),
    sa.Column('tender_fee', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('tender_type', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('procurement_type', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('work_location', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('withdrawal_allowed', sa.Boolean(), nullable=True),
    sa.Column('form_of_contract', sa.String(length=100), nullable=True),
    sa.Column('payment_mode', sa.String(length=100), nullable=True),
    sa.Column('work_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenders_tender_id'), 'tenders', ['tender_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenders_tender_id'), table_name='tenders')
    op.drop_table('tenders')
    # ### end Alembic commands ###
